# Generated by Django 5.1.3 on 2025-12-03 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('raid', 'Raid'), ('dungeon', 'Dungeon'), ('nightfall', 'Nightfall'), ('crucible', 'Crucible'), ('gambit', 'Gambit'), ('strike', 'Strike'), ('patrol', 'Patrol/Exploration'), ('seasonal', 'Seasonal Activity'), ('exotic', 'Exotic Quest'), ('other', 'Other')], max_length=50)),
                ('max_members', models.IntegerField(default=6)),
                ('current_members_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('requires_mic', models.BooleanField(default=False)),
                ('min_power_level', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_applications', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='parties.party')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Application',
                'verbose_name_plural': 'Party Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('party', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('kicked', 'Kicked')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='parties.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Member',
                'verbose_name_plural': 'Party Members',
                'ordering': ['joined_at'],
                'unique_together': {('party', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PartyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='parties.party')),
            ],
            options={
                'verbose_name': 'Party Tag',
                'verbose_name_plural': 'Party Tags',
                'unique_together': {('party', 'name')},
            },
        ),
    ]
