# Generated by Django 5.1.3 on 2025-12-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_destinyactivitytype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinyactivitytype',
            name='canonical_entry',
            field=models.ForeignKey(blank=True, help_text='Points to canonical entry if this is a duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='parties.destinyactivitytype'),
        ),
        migrations.AddField(
            model_name='destinyactivitytype',
            name='duplicate_group_name',
            field=models.CharField(blank=True, db_index=True, help_text='Group identifier for duplicate entries with same name', max_length=200),
        ),
        migrations.AddField(
            model_name='destinyactivitytype',
            name='is_canonical',
            field=models.BooleanField(db_index=True, default=True, help_text='True if this is the canonical/primary entry for this name'),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='needs_manual_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for activities that could not be parsed automatically'),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='original_name',
            field=models.CharField(blank=True, db_index=True, help_text='Original name from Bungie API before parsing', max_length=200),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='parsed_clean_name',
            field=models.CharField(blank=True, help_text='Activity name with difficulty/mode information removed', max_length=200),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='parsed_difficulty',
            field=models.CharField(blank=True, db_index=True, help_text='Extracted difficulty (Heroic, Legend, Master, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='parsed_mode',
            field=models.CharField(blank=True, db_index=True, help_text='Extracted mode (Matchmade, Private, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='destinyspecificactivity',
            name='parsing_notes',
            field=models.TextField(blank=True, help_text='Notes about parsing decisions for manual review'),
        ),
    ]
