# Generated by Django 5.1.3 on 2025-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BungieUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('bungie_membership_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('bungie_membership_type', models.IntegerField(choices=[(1, 'Xbox'), (2, 'PlayStation'), (3, 'Steam'), (4, 'Blizzard'), (5, 'Stadia'), (6, 'Epic Games'), (254, 'BungieNext')])),
                ('display_name', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('icon_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bungie_global_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bungie_global_display_name_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Bungie User',
                'verbose_name_plural': 'Bungie Users',
            },
        ),
    ]
