# Generated by Django 5.1.3 on 2025-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungieuser',
            name='is_admin_account',
            field=models.BooleanField(default=False, help_text='True if this is a username/password admin account (not Bungie OAuth)'),
        ),
        migrations.AddField(
            model_name='bungieuser',
            name='username',
            field=models.CharField(blank=True, help_text='For admin accounts only (not used for Bungie OAuth users)', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bungieuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
