# Generated by Django 5.1.3 on 2025-12-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(db_index=True, max_length=50)),
                ('membership_type', models.IntegerField(choices=[(1, 'Xbox'), (2, 'PlayStation'), (3, 'Steam'), (4, 'Blizzard'), (5, 'Stadia'), (6, 'Epic Games'), (10, 'Demon'), (254, 'BungieNext')])),
                ('display_name', models.CharField(max_length=255)),
                ('bungie_global_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bungie_global_display_name_code', models.CharField(blank=True, max_length=10, null=True)),
                ('icon_path', models.CharField(blank=True, max_length=500, null=True)),
                ('active_triumph_score', models.IntegerField(default=0)),
                ('lifetime_triumph_score', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destiny Player',
                'verbose_name_plural': 'Destiny Players',
                'indexes': [models.Index(fields=['membership_type', 'membership_id'], name='players_des_members_66ed8b_idx'), models.Index(fields=['bungie_global_display_name'], name='players_des_bungie__c9f738_idx'), models.Index(fields=['last_updated'], name='players_des_last_up_deddbb_idx')],
                'unique_together': {('membership_id', 'membership_type')},
            },
        ),
        migrations.CreateModel(
            name='DestinyCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(db_index=True, max_length=50)),
                ('class_type', models.IntegerField(choices=[(0, 'Titan'), (1, 'Hunter'), (2, 'Warlock')])),
                ('race_type', models.IntegerField(blank=True, choices=[(0, 'Human'), (1, 'Awoken'), (2, 'Exo')], null=True)),
                ('gender_type', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True)),
                ('light_level', models.IntegerField(default=0)),
                ('emblem_path', models.CharField(blank=True, max_length=500)),
                ('emblem_background_path', models.CharField(blank=True, max_length=500)),
                ('date_last_played', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='players.destinyplayer')),
            ],
            options={
                'verbose_name': 'Destiny Character',
                'verbose_name_plural': 'Destiny Characters',
                'ordering': ['-date_last_played'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTriumphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_triumph_score', models.IntegerField()),
                ('lifetime_triumph_score', models.IntegerField()),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triumph_snapshots', to='players.destinyplayer')),
            ],
            options={
                'verbose_name': 'Player Triumph Snapshot',
                'verbose_name_plural': 'Player Triumph Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='CharacterLightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_level', models.IntegerField()),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_snapshots', to='players.destinycharacter')),
            ],
            options={
                'verbose_name': 'Character Light Snapshot',
                'verbose_name_plural': 'Character Light Snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('character', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='destinycharacter',
            index=models.Index(fields=['character_id'], name='players_des_charact_f8322c_idx'),
        ),
        migrations.AddIndex(
            model_name='destinycharacter',
            index=models.Index(fields=['class_type'], name='players_des_class_t_a7fdbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='destinycharacter',
            unique_together={('player', 'character_id')},
        ),
        migrations.AddIndex(
            model_name='playertriumphsnapshot',
            index=models.Index(fields=['snapshot_date'], name='players_pla_snapsho_cce7d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playertriumphsnapshot',
            unique_together={('player', 'snapshot_date')},
        ),
    ]
