# Generated by Django 5.1.3 on 2025-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_light_level', models.FloatField(default=0)),
                ('stddev_light_level', models.FloatField(default=0)),
                ('light_level_distribution', models.JSONField(default=dict)),
                ('avg_triumph_score', models.FloatField(default=0)),
                ('stddev_triumph_score', models.FloatField(default=0)),
                ('triumph_score_distribution', models.JSONField(default=dict)),
                ('titan_count', models.IntegerField(default=0)),
                ('hunter_count', models.IntegerField(default=0)),
                ('warlock_count', models.IntegerField(default=0)),
                ('avg_play_time_hours', models.FloatField(default=0)),
                ('stddev_play_time_hours', models.FloatField(default=0)),
                ('play_time_distribution', models.JSONField(default=dict)),
                ('total_players', models.IntegerField(default=0)),
                ('total_characters', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Statistics Cache',
                'verbose_name_plural': 'Global Statistics Caches',
            },
        ),
        migrations.AddField(
            model_name='destinycharacter',
            name='minutes_played_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
