# Generated by Django 5.1.3 on 2025-12-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_globalstatisticscache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstatisticscache',
            name='class_statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='kurtosis_light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='kurtosis_play_time_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='kurtosis_triumph_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='max_light_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='max_triumph_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='median_light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='median_play_time_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='median_triumph_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='min_light_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='min_triumph_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q1_light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q1_play_time_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q1_triumph_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q3_light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q3_play_time_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='q3_triumph_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='skewness_light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='skewness_play_time_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='skewness_triumph_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
