# Generated by Django 5.1.3 on 2025-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_add_extended_statistics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstatisticscache',
            name='current_power_cap',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='globalstatisticscache',
            name='power_cap_season_hash',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
