# Generated by Django 5.1.3 on 2025-12-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinyActivity',
            fields=[
                ('hash', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=500)),
                ('has_icon', models.BooleanField(default=False)),
                ('redacted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destiny Activity',
                'verbose_name_plural': 'Destiny Activities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='fireteams_d_is_acti_0914c3_idx')],
            },
        ),
    ]
