# Generated by Django 5.1.3 on 2025-12-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireteams', '0002_destinyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Activity from Bungie API manifest', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='fireteams.destinyactivity'),
        ),
        migrations.AlterField(
            model_name='party',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('raid', 'Raid'), ('dungeon', 'Dungeon'), ('nightfall', 'Nightfall'), ('crucible', 'Crucible'), ('gambit', 'Gambit'), ('strike', 'Strike'), ('patrol', 'Patrol/Exploration'), ('seasonal', 'Seasonal Activity'), ('exotic', 'Exotic Quest'), ('other', 'Other')], help_text='DEPRECATED: Use activity field instead', max_length=50, null=True),
        ),
    ]
