# Generated by Django 5.1.3 on 2025-12-04 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireteams', '0003_party_activity_alter_party_activity_type'),
    ]

    operations = [
        # Step 1: Rename model first
        migrations.RenameModel(
            old_name='DestinyActivity',
            new_name='DestinyActivityType',
        ),
        # Step 2: Alter model options after rename
        migrations.AlterModelOptions(
            name='destinyactivitytype',
            options={'ordering': ['name'], 'verbose_name': 'Destiny Activity Type', 'verbose_name_plural': 'Destiny Activity Types'},
        ),
        migrations.AlterModelTable(
            name='destinyactivitytype',
            table='fireteams_destinyactivity',
        ),
        # Step 3: Update existing fields
        migrations.AlterField(
            model_name='party',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use selected_* fields instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_parties', to='fireteams.destinyactivitytype'),
        ),
        migrations.AlterField(
            model_name='party',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('raid', 'Raid'), ('dungeon', 'Dungeon'), ('nightfall', 'Nightfall'), ('crucible', 'Crucible'), ('gambit', 'Gambit'), ('strike', 'Strike'), ('patrol', 'Patrol/Exploration'), ('seasonal', 'Seasonal Activity'), ('exotic', 'Exotic Quest'), ('other', 'Other')], help_text='DEPRECATED: Use selected_* fields instead', max_length=50, null=True),
        ),
        # Step 4: Create new models
        migrations.CreateModel(
            name='DestinyActivityMode',
            fields=[
                ('hash', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=500)),
                ('has_icon', models.BooleanField(default=False)),
                ('mode_type', models.IntegerField(default=0)),
                ('activity_mode_category', models.IntegerField(default=0)),
                ('is_team_based', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('redacted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destiny Activity Mode',
                'verbose_name_plural': 'Destiny Activity Modes',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='fireteams_d_is_acti_5c28d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinySpecificActivity',
            fields=[
                ('hash', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_path', models.CharField(blank=True, max_length=500)),
                ('has_icon', models.BooleanField(default=False)),
                ('activity_level', models.IntegerField(default=0)),
                ('activity_light_level', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=0)),
                ('is_playlist', models.BooleanField(default=False)),
                ('redacted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_activities', to='fireteams.destinyactivitytype')),
            ],
            options={
                'verbose_name': 'Destiny Specific Activity',
                'verbose_name_plural': 'Destiny Specific Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityModeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fireteams.destinyactivitymode')),
                ('specific_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_modes', to='fireteams.destinyspecificactivity')),
            ],
            options={
                'verbose_name': 'Activity Mode Availability',
                'verbose_name_plural': 'Activity Mode Availabilities',
            },
        ),
        # Step 5: Add new FK fields to Party
        migrations.AddField(
            model_name='party',
            name='selected_activity_type',
            field=models.ForeignKey(blank=True, help_text='Tier 1: Activity Type (Raid, Dungeon, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties_by_type', to='fireteams.destinyactivitytype'),
        ),
        migrations.AddField(
            model_name='party',
            name='selected_specific_activity',
            field=models.ForeignKey(blank=True, help_text='Tier 2: Specific Activity (Deep Stone Crypt, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='fireteams.destinyspecificactivity'),
        ),
        migrations.AddField(
            model_name='party',
            name='selected_activity_mode',
            field=models.ForeignKey(blank=True, help_text='Tier 3: Difficulty/Mode (Master, Heroic, etc.) - Optional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties_by_mode', to='fireteams.destinyactivitymode'),
        ),
        # Step 6: Add indexes and constraints
        migrations.AddIndex(
            model_name='destinyspecificactivity',
            index=models.Index(fields=['activity_type', 'is_active'], name='fireteams_d_activit_1f4f12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activitymodeavailability',
            unique_together={('specific_activity', 'activity_mode')},
        ),
    ]
