# Generated by Django 5.1.3 on 2025-12-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireteams', '0006_rename_party_to_fireteam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireteam',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use selected_* fields instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_fireteams', to='fireteams.destinyactivitytype'),
        ),
        migrations.AlterField(
            model_name='fireteam',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fireteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fireteam',
            name='selected_activity_mode',
            field=models.ForeignKey(blank=True, help_text='Tier 3: Difficulty/Mode (Master, Heroic, etc.) - Optional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fireteams_by_mode', to='fireteams.destinyactivitymode'),
        ),
        migrations.AlterField(
            model_name='fireteam',
            name='selected_activity_type',
            field=models.ForeignKey(blank=True, help_text='Tier 1: Activity Type (Raid, Dungeon, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fireteams_by_type', to='fireteams.destinyactivitytype'),
        ),
        migrations.AlterField(
            model_name='fireteam',
            name='selected_specific_activity',
            field=models.ForeignKey(blank=True, help_text='Tier 2: Specific Activity (Deep Stone Crypt, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fireteams', to='fireteams.destinyspecificactivity'),
        ),
        migrations.AlterField(
            model_name='fireteamapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fireteam_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fireteamapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fireteam_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fireteammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fireteam_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
