# Generated by Django 5.1.3 on 2025-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireteams', '0007_alter_fireteam_activity_alter_fireteam_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireteam',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
